# Generated by Django 5.2.1 on 2025-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('fecha_checkin', models.DateTimeField()),
                ('fecha_checkout', models.DateTimeField()),
                ('duracion', models.IntegerField(default=0)),
            ],
        ),
    ]
