# Generated by Django 5.2.1 on 2025-05-28 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_timerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='fecha_checkin',
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='fecha_checkout',
        ),
        migrations.AddField(
            model_name='timerecord',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='duracion',
            field=models.DateField(),
        ),
    ]
